# Generated by Django 6.0.7 on 2026-07-30 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_eui', models.CharField(max_length=16, unique=True)),
                ('latest_status', models.CharField(choices=[('passing', 'Passing'), ('failing', 'Failing'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_cnt', models.PositiveBigIntegerField()),
                ('data', models.TextField()),
                ('decoded_hex', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('passing', 'Passing'), ('failing', 'Failing'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('rx_info', models.JSONField(blank=True, default=list)),
                ('tx_info', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payloads', to='telemetry.device')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['device', '-created_at'], name='payload_device_recent_idx')],
                'constraints': [models.UniqueConstraint(fields=('device', 'f_cnt'), name='unique_device_f_cnt')],
            },
        ),
    ]
