# Generated by Django 6.0.7 on 2026-07-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payload',
            name='object',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
